name: build

on: [push]

jobs:
  build-ssr:
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./ssr

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          brew update
          brew install python3 || : # python doesn't need to be linked
          brew install pkg-config cairo pango libpng jpeg giflib librsvg
          pip install setuptools

      - name: Run CI
        run: |
          npm install
          npm run ci

  build-3d:
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./3d

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run CI
        run: |
          npm install
          npm run ci

      - name: Upload snapshots to GitHub Actions Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: |
            3d/__tests__/e2e/snapshots/*-actual.*
            3d/__tests__/e2e/snapshots/*-diff.*
          retention-days: 1
